# Generated by Django 3.2 on 2023-05-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
