# Generated by Django 3.2 on 2023-05-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0003_libraryuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryUser',
        ),
    ]
