# Generated by Django 3.2 on 2023-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('literal_comment', models.CharField(max_length=200, verbose_name='用户的文字评论')),
                ('date', models.DateTimeField(null=True, verbose_name='该条评论的时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='该条评论是否审核过')),
                ('image_comment', models.ImageField(null=True, upload_to='', verbose_name='用户的图片评论')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('comment_permission', models.BooleanField(default=False, verbose_name='用户评论权限')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
    ]
