# Generated by Django 3.2 on 2023-05-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalRelicsData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cat1', models.CharField(blank=True, max_length=255, null=True)),
                ('cat2', models.CharField(blank=True, max_length=255, null=True)),
                ('cat3', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('makers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('museum', models.CharField(blank=True, max_length=255, null=True)),
                ('time_period', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('geography', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cultural_relics_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_sex', models.IntegerField(blank=True, null=True)),
                ('user_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('user_comment', models.IntegerField(blank=True, null=True)),
                ('user_login', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
