# Generated by Django 3.2 on 2023-05-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('collection_name', models.CharField(blank=True, db_column='Collection_name', max_length=200, null=True)),
                ('museum', models.CharField(blank=True, db_column='Museum', max_length=200, null=True)),
                ('materials', models.CharField(blank=True, db_column='Materials', max_length=200, null=True)),
                ('creation_date', models.CharField(blank=True, db_column='Creation_date', max_length=200, null=True)),
                ('discription', models.CharField(blank=True, db_column='Discription', max_length=500, null=True)),
                ('image_url', models.CharField(blank=True, db_column='Image_url', max_length=500, null=True)),
            ],
            options={
                'db_table': 'collections',
                'managed': True,
            },
        ),
    ]
